spring.application.name=cpl-orm

spring.datasource.url=jdbc:mysql://localhost:3306/cpl_db
spring.datasource.username=root
spring.datasource.password=root
spring.data.jdbc.dialect=mysql

spring.jpa.hibernate.ddl-auto=update

security.jwt.secret=iuqwdkbakcbiuy12983yoncljlakshdha12313no12y43981hdnamndbiqhjr

logging.level.org.springframework.security=TRACE