spring.application.name=cpl-orm

spring.datasource.url=jdbc:mysql://localhost:3306/cpl_db
spring.datasource.username=root
spring.datasource.password=root
spring.data.jdbc.dialect=mysql

spring.jpa.hibernate.ddl-auto=update